let isAdmin=false;
async function loadAdmin(){try{const r=await fetch('/api/admin/me');const d=await r.json();isAdmin=!!d.admin;syncAdminUI();if(isAdmin){document.getElementById('adminPanel').classList.add('show');refreshStatus()}}catch(e){}}
function syncAdminUI(){const lock=document.getElementById('chatLock');if(lock)lock.classList.toggle('hidden',isAdmin);document.getElementById('adminPanel')?.classList.toggle('show',isAdmin);document.getElementById('adminBtn')?.classList.toggle('logged',isAdmin)}
function openAdmin(){document.getElementById('adminModal').classList.add('show');setTimeout(()=>document.getElementById('adminPassword').focus(),50)}
function closeAdmin(){document.getElementById('adminModal').classList.remove('show');document.getElementById('loginError').textContent=''}
document.getElementById('adminBtn').onclick=openAdmin;document.getElementById('unlockChat').onclick=openAdmin;document.getElementById('closeAdmin').onclick=closeAdmin;
document.getElementById('loginBtn').onclick=async()=>{const password=document.getElementById('adminPassword').value;const er=document.getElementById('loginError');er.textContent='';try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)throw Error(d.error||'Login failed');isAdmin=true;document.getElementById('adminPassword').value='';closeAdmin();syncAdminUI();refreshStatus();toast('Admin access unlocked')}catch(e){er.textContent=e.message}};
document.getElementById('adminPassword').addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('loginBtn').click()});
document.getElementById('logoutBtn').onclick=async()=>{await fetch('/api/admin/logout',{method:'POST'});isAdmin=false;syncAdminUI();toast('Admin logged out')};
async function refreshStatus(){if(!isAdmin)return;try{const r=await fetch('/api/admin/status');const d=await r.json();if(!r.ok)throw Error(d.error);document.getElementById('siteStatus').textContent='ONLINE';document.getElementById('apiStatus').textContent=d.openaiConfigured?'CONNECTED':'NOT CONFIGURED';document.getElementById('siteVersion').textContent=d.version;document.getElementById('siteUptime').textContent=formatUptime(d.uptimeSeconds);document.getElementById('updateBox').textContent=d.updateManifestConfigured?'Remote update manifest is configured. Tap Check for Updates.':'Update Center is ready. Use Copy Update Request when you want ChatGPT to prepare a fresh update package.'}catch(e){document.getElementById('siteStatus').textContent='OFFLINE / ERROR';toast(e.message)}}
function formatUptime(s){s=Number(s)||0;const d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);return `${d?d+'d ':''}${h? h+'h ':''}${m}m`}
document.getElementById('refreshStatus').onclick=refreshStatus;
document.getElementById('checkUpdates').onclick=async()=>{if(!isAdmin)return openAdmin();const box=document.getElementById('updateBox');box.textContent='Checking for updates…';try{const r=await fetch('/api/admin/updates');const d=await r.json();if(!r.ok)throw Error(d.error);if(d.configured){box.textContent=d.message||(`Current version: ${d.currentVersion}. Latest: ${d.latestVersion||'unknown'}.`)}else box.textContent=d.message}catch(e){box.textContent='⚠️ '+e.message}};
document.getElementById('copyUpdateRequest').onclick=async()=>{const text='Update my FRANCIS AND ISAAC AI BOT to the latest modern version. Keep the current design/features, fix any broken deployment/assets, add requested new features, and return a complete deployment-ready ZIP.';try{await navigator.clipboard.writeText(text);toast('Update request copied — send it to ChatGPT with your current ZIP.')}catch(e){toast('Copy failed; select and copy the request from the update panel.')}document.getElementById('updateBox').textContent=text};
loadAdmin();
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let previousResponseId=null;
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>x.classList.remove('show'),2600)}
$('#menuBtn').onclick=()=>$('#drawer').classList.toggle('open');
$$('[data-scroll]').forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'});$('#drawer').classList.remove('open');$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x===b))});
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.fiTheme=document.body.classList.contains('light')?'light':'dark';$('#themeBtn').textContent=document.body.classList.contains('light')?'☀':'☾'};if(localStorage.fiTheme==='light'){$('#themeBtn').click()}
async function sendChat(){if(!isAdmin){openAdmin();return}const input=$('#chatInput'),text=input.value.trim();if(!text)return;$('#chatResponse').textContent='Thinking…';input.value='';try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,previousResponseId,mode:'general'})});const d=await r.json();if(!r.ok)throw Error(d.error||'AI request failed');$('#chatResponse').textContent=d.text;previousResponseId=d.responseId||previousResponseId}catch(e){$('#chatResponse').textContent='⚠️ '+e.message;toast('AI request failed')}}$('#chatForm').onsubmit=e=>{e.preventDefault();sendChat()};
$('#imageBtn').onclick=async()=>{const p=$('#imagePrompt').value.trim();if(!p)return toast('Describe the image first.');$('#imageResult').innerHTML='<span>Creating your image…</span>';try{const r=await fetch('/api/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p,size:'1536x1024',quality:'high'})});const d=await r.json();if(!r.ok)throw Error(d.error||'Image generation failed');$('#imageResult').innerHTML=`<img src="${d.image}" alt="Generated image"><a download="francis-isaac-image.png" href="${d.image}">Download image</a>`}catch(e){$('#imageResult').textContent='⚠️ '+e.message}};
$('#videoBtn').onclick=async()=>{const p=$('#videoPrompt').value.trim();if(!p)return toast('Describe the video first.');$('#videoStatus').textContent='Starting video generation…';try{const r=await fetch('/api/video',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p,model:$('#videoModel').value,seconds:$('#videoSeconds').value,size:'1280x720'})});const d=await r.json();if(!r.ok)throw Error(d.error||'Video generation failed');for(;;){const s=await fetch('/api/video/'+encodeURIComponent(d.id)),j=await s.json();if(!s.ok)throw Error(j.error||'Status failed');$('#videoStatus').textContent=(j.status||'processing')+' '+Math.round((j.progress||0)*100)+'%';if(j.status==='completed'){const v=$('#videoResult');v.src='/api/video/'+encodeURIComponent(d.id)+'/content';v.style.display='block';$('#videoStatus').textContent='✅ Video ready';break}if(j.status==='failed')throw Error(j.error?.message||'Video failed');await new Promise(r=>setTimeout(r,5000))}}catch(e){$('#videoStatus').textContent='⚠️ '+e.message}};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;$('#voiceBtn').onclick=()=>{if(!SR)return toast('Voice input is not supported in this browser.');const r=new SR();r.lang='en-GH';r.onstart=()=>{$('#voiceText').textContent='Listening…'};r.onresult=e=>{$('#voiceText').textContent=e.results[0][0].transcript;$('#chatInput').value=e.results[0][0].transcript;sendChat()};r.onerror=e=>toast('Microphone: '+e.error);r.start()};
$$('.tool').forEach(b=>b.onclick=()=>{const name=b.querySelector('b')?.textContent||'Tool';toast(name+' opened — connect its API endpoint to activate it.');if(b.dataset.tool==='chat')document.querySelector('#chat').scrollIntoView({behavior:'smooth'});if(b.dataset.tool==='stt')$('#voiceStudio').scrollIntoView({behavior:'smooth'});});
$$('[data-open]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.open+'Studio').scrollIntoView({behavior:'smooth'}));
$$('[data-insert-image]').forEach(b=>b.onclick=()=>{$('#imagePrompt').value=b.dataset.insertImage+' — make it modern, cinematic and high quality.';$('#imagePrompt').focus()});
